apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: wxd-deployment-pipeline
  namespace: wxd
spec:
  params:
    - name: git-url
      type: string
      description: Git repository URL
    - name: git-revision
      type: string
      default: main
      description: Git revision (branch/tag)
    - name: helm-values-file
      type: string
      default: values.yaml
    - name: helm-secret-file
      type: string
      default: values-secret.yaml
    - name: namespace
      type: string
      default: wxd
    - name: helm-timeout
      type: string
      default: 120m
  
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: validate-helm-chart
      runAfter: [clone-repo]
      taskRef:
        name: helm-lint
      params:
        - name: charts_dir
          value: .
        - name: helm_version
          value: v3.14.0
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: create-namespace
      runAfter: [validate-helm-chart]
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            #!/bin/bash
            set -e
            echo "Creating namespace $(params.namespace)..."
            oc create namespace $(params.namespace) --dry-run=client -o yaml | oc apply -f -
            echo "âœ… Namespace created/verified"
            
            echo "Setting up RBAC..."
            oc policy add-role-to-user edit system:serviceaccount:$(params.namespace):default -n $(params.namespace) || true
            echo "âœ… RBAC configured"

    - name: deploy-wxd-helm
      runAfter: [create-namespace]
      taskRef:
        name: helm-upgrade-from-source
      params:
        - name: helm_upgrade_extra_params
          value: |
            --namespace $(params.namespace) \
            --create-namespace \
            --timeout $(params.helm-timeout) \
            --wait \
            --wait-for-jobs \
            --atomic \
            --cleanup-on-fail
        - name: helm_version
          value: v3.14.0
        - name: values
          value: |
            -f ./$(params.helm-values-file) \
            -f ./$(params.helm-secret-file)
        - name: release_name
          value: wxd
        - name: release_namespace
          value: $(params.namespace)
        - name: overwrite_values
          value: ""
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: wait-for-pods
      runAfter: [deploy-wxd-helm]
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            #!/bin/bash
            set -e
            NAMESPACE=$(params.namespace)
            MAX_ATTEMPTS=120
            SLEEP_TIME=20
            attempt=1
            
            echo "â³ Waiting for all pods in namespace '$NAMESPACE' to be Running/Completed..."
            echo "   Max attempts: $MAX_ATTEMPTS, Sleep: ${SLEEP_TIME}s"
            
            while [ $attempt -le $MAX_ATTEMPTS ]; do
              not_ready=$(oc get pods -n "$NAMESPACE" --no-headers \
                | grep -vE 'Running|Completed' \
                | wc -l)
            
              if [ "$not_ready" -eq 0 ]; then
                echo "âœ… All pods are running in namespace '$NAMESPACE'."
                break
              fi
            
              echo "[$attempt/$MAX_ATTEMPTS] Still waiting... ($not_ready pods not ready)"
              attempt=$((attempt+1))
              sleep $SLEEP_TIME
            done
            
            if [ $attempt -gt $MAX_ATTEMPTS ]; then
              echo "âš ï¸ Timeout waiting for pods. Current status:"
            fi
            
            echo ""
            echo "Pod Status:"
            oc get pods -n "$NAMESPACE"

    - name: create-routes
      runAfter: [wait-for-pods]
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            #!/bin/bash
            set -e
            NAMESPACE=$(params.namespace)
            DOMAIN=$(oc get ingresscontroller default -n openshift-ingress-operator -o jsonpath='{.status.domain}' 2>/dev/null || echo "apps.example.com")
            
            echo "Creating routes for WXD services..."
            echo "Using domain: $DOMAIN"
            
            # Route for lhconsole-ui
            oc create route passthrough lhconsole-ui-route \
              --service=lhconsole-ui-svc \
              --hostname=lhconsole-ui.$DOMAIN \
              -n $NAMESPACE --dry-run=client -o yaml | oc apply -f -
            echo "âœ… lhconsole-ui route created"
            
            # Route for minio
            oc create route edge ibm-lh-minio-route \
              --service=ibm-lh-minio-svc \
              --hostname=minio.$DOMAIN \
              -n $NAMESPACE --dry-run=client -o yaml | oc apply -f -
            echo "âœ… minio route created"
            
            # Route for mds-thrift
            oc create route edge ibm-lh-mds-thrift-route \
              --service=ibm-lh-mds-thrift-svc \
              --hostname=mds-thrift.$DOMAIN \
              -n $NAMESPACE --dry-run=client -o yaml | oc apply -f -
            echo "âœ… mds-thrift route created"

    - name: display-endpoints
      runAfter: [create-routes]
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            #!/bin/bash
            set -e
            NAMESPACE=$(params.namespace)
            
            echo ""
            echo "=========================================================="
            echo "âœ… WXD Deployment Complete!"
            echo "=========================================================="
            echo ""
            echo "ðŸ“‹ Routes:"
            oc get routes -n $NAMESPACE -o wide
            echo ""
            echo "ðŸ“Š Pods:"
            oc get pods -n $NAMESPACE
            echo ""
            echo "ðŸ”— Access Points:"
            
            CONSOLE_ROUTE=$(oc get route lhconsole-ui-route -n $NAMESPACE -o jsonpath='{.spec.host}' 2>/dev/null || echo "lhconsole-ui.<domain>")
            echo "   ðŸŒ Console UI: https://${CONSOLE_ROUTE}"
            
            MINIO_ROUTE=$(oc get route ibm-lh-minio-route -n $NAMESPACE -o jsonpath='{.spec.host}' 2>/dev/null || echo "minio.<domain>")
            echo "   ðŸ“¦ MinIO: https://${MINIO_ROUTE}:9001"
            
            MDS_ROUTE=$(oc get route ibm-lh-mds-thrift-route -n $NAMESPACE -o jsonpath='{.spec.host}' 2>/dev/null || echo "mds-thrift.<domain>")
            echo "   ðŸ“¡ MDS Thrift: https://${MDS_ROUTE}"
            
            echo ""
            echo "=========================================================="

  workspaces:
    - name: shared-workspace

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: wxd-deployment-run
  namespace: wxd
spec:
  pipelineRef:
    name: wxd-deployment-pipeline
  params:
    - name: git-url
      value: "https://your-git-repo.git"
    - name: git-revision
      value: "main"
    - name: namespace
      value: "wxd"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
  serviceAccountName: pipeline
  timeout: 3h

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: wxd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-wxd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: wxd