apiVersion: v1
data:
  AMS_URL:  "https://{{ .Values.service.consoleAms.name }}:{{ .Values.service.consoleAms.port }}"
  CM_PATH: "{{ .Values.config.wxdLaunchCm.CM_PATH }}"
  CONSOLE_API_URL: "https://{{ .Values.service.consoleApi.name }}:{{ .Values.service.consoleApi.port }}"
  COORDINATOR_HOST: "{{ .Values.config.wxdLaunchCm.COORDINATOR_HOST }}"
  COORDINATOR_PORT: "{{ .Values.config.wxdLaunchCm.COORDINATOR_PORT }}"
  CPG_URL: "{{ .Values.config.wxdLaunchCm.CPG_URL }}"
  DEMO_MODE: "{{ .Values.config.wxdLaunchCm.DEMO_MODE }}"
  GROUP: "{{ .Values.config.wxdLaunchCm.GROUP }}"
  HMS_CONNECTIONPOOL_MAXPOOLSIZE: "{{ .Values.config.wxdLaunchCm.HMS_CONNECTIONPOOL_MAXPOOLSIZE }}"
  HMS_THRIFT_URL: "{{ .Values.config.wxdLaunchCm.HMS_THRIFT_URL }}"
  HMS_URL: "{{ .Values.config.wxdLaunchCm.HMS_URL }}"
  INGESTION_SVC_URI: "{{ .Values.config.wxdLaunchCm.INGESTION_SVC_URI }}"
  INSTANCE_ID: "{{ .Values.config.wxdLaunchCm.INSTANCE_ID }}"
  JAVA_SVC_URI: "{{ .Values.config.wxdLaunchCm.JAVA_SVC_URI }}"
  LAKEHOUSE_LOGFILEPATH: "{{ .Values.config.wxdLaunchCm.LAKEHOUSE_LOGFILEPATH }}"
  LH_AUTH_USERNAME: "{{ .Values.config.wxdLaunchCm.LH_AUTH_USERNAME }}"
  LH_CONSOLE_API_URL: "https://{{ .Values.service.consoleApi.name }}:{{ .Values.service.consoleApi.port }}"
  LH_CONTEXT: "{{ .Values.config.wxdLaunchCm.LH_CONTEXT }}"
  LH_DEFAULT_BUCKET_LIST: "{{ .Values.config.wxdLaunchCm.LH_DEFAULT_BUCKET_LIST }}"
  LH_DEFAULT_CATALOG_LIST: "{{ .Values.config.wxdLaunchCm.LH_DEFAULT_CATALOG_LIST }}"
  LH_DEV_HTPASSWD_FILE: "{{ .Values.config.wxdLaunchCm.LH_DEV_HTPASSWD_FILE }}"
  LH_DEV_ROLES_FILE: "{{ .Values.config.wxdLaunchCm.LH_DEV_ROLES_FILE }}"
  LH_ENV: "{{ .Values.config.wxdLaunchCm.LH_ENV }}"
  LH_HIVE_BUCKET: "{{ .Values.config.wxdLaunchCm.LH_HIVE_BUCKET }}"
  LH_HIVE_CATALOG: "{{ .Values.config.wxdLaunchCm.LH_HIVE_CATALOG }}"
  LH_HMS_PORT: "{{ .Values.config.wxdLaunchCm.LH_HMS_PORT }}"
  LH_INSTANCE_ID: "{{ .Values.config.wxdLaunchCm.LH_INSTANCE_ID }}"
  LH_INSTANCE_NAME: "{{ .Values.config.wxdLaunchCm.LH_INSTANCE_NAME }}"
  LH_METASTORE_DB: "{{ .Values.config.wxdLaunchCm.LH_METASTORE_DB }}"
  LH_MILVUS_BUCKET: "{{ .Values.config.wxdLaunchCm.LH_MILVUS_BUCKET }}"
  LH_PLUGINS_BUCKET_LOCATION: "{{ .Values.config.wxdLaunchCm.LH_PLUGINS_BUCKET_LOCATION }}"
  LH_PRESTISSIMO: "{{ .Values.config.wxdLaunchCm.LH_PRESTISSIMO }}"
  LH_QHMM_BUCKET_LOCATION: "{{ .Values.config.wxdLaunchCm.LH_QHMM_BUCKET_LOCATION }}"
  LH_S3_BUCKET: "{{ .Values.config.wxdLaunchCm.LH_S3_BUCKET }}"
  LH_S3_CATALOG: "{{ .Values.config.wxdLaunchCm.LH_S3_CATALOG }}"
  LH_S3_REGION: "{{ .Values.config.wxdLaunchCm.LH_S3_REGION }}"
  LH_S3_URL: "{{ .Values.config.wxdLaunchCm.LH_S3_URL }}"
  LH_SA: "{{ .Values.config.wxdLaunchCm.LH_SA }}"
  LH_SERVER_PRIVATE_KEY: "{{ .Values.config.wxdLaunchCm.LH_SERVER_PRIVATE_KEY }}"
  LH_SERVER_PUBLIC_KEY: "{{ .Values.config.wxdLaunchCm.LH_SERVER_PUBLIC_KEY }}"
  LH_SYSTEM_BUCKET: "{{ .Values.config.wxdLaunchCm.LH_SYSTEM_BUCKET }}"
  LH_SYSTEM_CATALOG: "{{ .Values.config.wxdLaunchCm.LH_SYSTEM_CATALOG }}"
  LH_WKC: "{{ .Values.config.wxdLaunchCm.LH_WKC }}"
  MDS_DB_CONNECTION_MAX_POOL_SIZE: "{{ .Values.config.wxdLaunchCm.MDS_DB_CONNECTION_MAX_POOL_SIZE }}"
  MDS_REST_URL: "{{ .Values.config.wxdLaunchCm.MDS_REST_URL }}"
  MDS_THRIFT_URL: "{{ .Values.config.wxdLaunchCm.MDS_THRIFT_URL }}"
  MILVUS_ETCD_ENDPOINT: "{{ .Values.config.wxdLaunchCm.MILVUS_ETCD_ENDPOINT }}"
  MILVUS_PRIVILEGES_PATH: "{{ .Values.config.wxdLaunchCm.MILVUS_PRIVILEGES_PATH }}"
  NODE_SVC_URI: "{{ .Values.config.wxdLaunchCm.NODE_SVC_URI }}"
  NODE_TLS_REJECT_UNAUTHORIZED: "{{ .Values.config.wxdLaunchCm.NODE_TLS_REJECT_UNAUTHORIZED }}"
  namespace: "{{ .Release.Namespace }}"
  PGCLIENTENCODING: "{{ .Values.config.wxdLaunchCm.PGCLIENTENCODING }}"
  POLICYMGR_EXTERNAL_URL: "{{ .Values.config.wxdLaunchCm.POLICYMGR_EXTERNAL_URL }}"
  POLICYMGR_HTTPS_KEYSTORE_FILE: "{{ .Values.config.wxdLaunchCm.POLICYMGR_HTTPS_KEYSTORE_FILE }}"
  POLICYMGR_HTTPS_KEYSTORE_KEYALIAS: "{{ .Values.config.wxdLaunchCm.POLICYMGR_HTTPS_KEYSTORE_KEYALIAS }}"
  POLICYMGR_HTTPS_KEYSTORE_PASSWORD: "{{ .Values.config.wxdLaunchCm.POLICYMGR_HTTPS_KEYSTORE_PASSWORD }}"
  POSTGRES_DB: "{{ .Values.global.postgresql.auth.database }}"
  POSTGRES_DB_NAME: "{{ .Values.global.postgresql.auth.database }}"
  POSTGRES_HOST: "{{ .Values.config.wxdLaunchCm.POSTGRES_HOST }}"
  POSTGRES_PASSWORD: "{{ .Values.global.postgresql.auth.password }}"
  POSTGRES_URI: "{{ .Values.config.wxdLaunchCm.POSTGRES_HOST }}"
  POSTGRES_USER: "{{ .Values.global.postgresql.auth.username }}"
  PRESTO_HISTORY_FILE: "{{ .Values.config.wxdLaunchCm.PRESTO_HISTORY_FILE }}"
  PRESTO_SERVER: "{{ .Values.config.wxdLaunchCm.PRESTO_SERVER }}"
  PRISMO: "{{ .Values.config.wxdLaunchCm.PRISMO }}"
  PUBLIC_CERT_URL: "{{ .Values.config.wxdLaunchCm.PUBLIC_CERT_URL }}"
  RANGER_ADMIN_PASSWORD: "{{ .Values.config.wxdLaunchCm.RANGER_ADMIN_PASSWORD }}"
  RANGER_CONNECTION_URI: "{{ .Values.config.wxdLaunchCm.RANGER_CONNECTION_URI }}"
  RANGER_KEYADMIN_PASSWORD: "{{ .Values.config.wxdLaunchCm.RANGER_KEYADMIN_PASSWORD }}"
  RANGER_PLUGIN_ENABLED: "{{ .Values.config.wxdLaunchCm.RANGER_PLUGIN_ENABLED }}"
  RANGER_POLICY_STORED: "{{ .Values.config.wxdLaunchCm.RANGER_POLICY_STORED }}"
  RANGER_SSL_CERT_PATH: "{{ .Values.config.wxdLaunchCm.RANGER_SSL_CERT_PATH }}"
  RANGER_TAGSYNC_PASSWORD: "{{ .Values.config.wxdLaunchCm.RANGER_TAGSYNC_PASSWORD }}"
  RANGER_USERSYNC_PASSWORD: "{{ .Values.config.wxdLaunchCm.RANGER_USERSYNC_PASSWORD }}"
  REQUESTS_CA_BUNDLE: "{{ .Values.config.wxdLaunchCm.REQUESTS_CA_BUNDLE }}"
  SSL_CERT_FILE: "{{ .Values.config.wxdLaunchCm.SSL_CERT_FILE }}"
  SSL_CRT: "{{ .Values.config.wxdLaunchCm.SSL_CRT }}"
  SSL_CUSTOM_CRT: "{{ .Values.config.wxdLaunchCm.SSL_CUSTOM_CRT }}"
  SSL_CUSTOM_KEY: "{{ .Values.config.wxdLaunchCm.SSL_CUSTOM_KEY }}"
  SSL_EXTERNAL_CRT: "{{ .Values.config.wxdLaunchCm.SSL_EXTERNAL_CRT }}"
  SSL_EXTERNAL_KEY: "{{ .Values.config.wxdLaunchCm.SSL_EXTERNAL_KEY }}"
  SSL_KEY: "{{ .Values.config.wxdLaunchCm.SSL_KEY }}"
  SSL_KS_FILE: "{{ .Values.config.wxdLaunchCm.SSL_KS_FILE }}"
  SSL_TS_FILE: "{{ .Values.config.wxdLaunchCm.SSL_TS_FILE }}"
  SSLTMPDIR: "{{ .Values.config.wxdLaunchCm.SSLTMPDIR }}"
  TRUST_STORE_PATH: "{{ .Values.config.wxdLaunchCm.TRUST_STORE_PATH }}"
  enableAuth: "{{ .Values.config.wxdLaunchCm.enableAuth }}"
  enableMDS: "{{ .Values.config.wxdLaunchCm.enableMDS }}"
  ZEN_ROUTE: "{{ .Values.service.consoleUi.name }}:{{ .Values.service.consoleUi.port }}"
  httpsPrefix: "https"
  SERVICE_APIKEY_USERNAME: "{{ .Values.config.wxdLaunchCm.SERVICE_APIKEY_USERNAME }}"
  SERVICE_TOKEN_USERNAME: "{{ .Values.config.wxdLaunchCm.SERVICE_TOKEN_USERNAME }}"
kind: ConfigMap
metadata:
  name: wxd-launch-cm
  namespace: "{{ .Release.Namespace }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"

# Made with Bob
