apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    function: spark-hb-create-trust-store
  name: spark-hb-create-trust-store
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      function: spark-hb-create-trust-store
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        function: spark-hb-create-trust-store
    spec:
      containers:
      - args:
        - bash /opt/ibm/entrypoint/create-trust-store-and-secret.sh changeit spark-hb-java-trust-store
          spark-hb-os-trust-store /opt/hb/icp4d-certs /opt/hb/custom-certs
        command:
        - /bin/bash
        - -c
        image: {{ .Values.images.registry }}/{{ .Values.images.image.sparkTruststore }}{{ .Values.images.tag.sparkTruststore }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls
            - /tmp/SUCCESS
          failureThreshold: 120
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: spark-hb-create-trust-store
        readinessProbe:
          exec:
            command:
            - ls
            - /tmp/SUCCESS
          failureThreshold: 120
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            ephemeral-storage: 100Mi
            memory: 256Mi
          requests:
            cpu: 100m
            ephemeral-storage: 100Mi
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/hb/icp4d-certs
          name: icp4d-certs
          readOnly: true
        - mountPath: /opt/ibm/entrypoint/
          name: spark-hb-create-trust-store-secret-script
        - mountPath: /opt/hb/custom-certs
          name: connection-ca-certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: {{ .Values.serviceAccount.wxdServiceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.wxdServiceAccount.name }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: icp4d-certs
        secret:
          defaultMode: 420
          secretName: internal-tls
      - configMap:
          defaultMode: 420
          items:
          - key: create-trust-store-and-secret.sh
            path: create-trust-store-and-secret.sh
          name: spark-hb-create-trust-store-secret-script
        name: spark-hb-create-trust-store-secret-script
      - name: connection-ca-certs
        secret:
          defaultMode: 420
          optional: true
          secretName: cpd-custom-ca-certs
