apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    function: spark-hb-nginx
  name: spark-hb-nginx
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "11"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      function: spark-hb-nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        function: spark-hb-nginx
    spec:
      containers:
      - args:
        - bash /tmp/nginx-resolver.sh /mnt/nginx;/usr/sbin/nginx
        command:
        - /bin/bash
        - -c
        image: {{ .Values.images.registry }}/{{ .Values.images.image.sparkNginx }}{{ .Values.images.tag.sparkNginx }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: 9999
          timeoutSeconds: 1
        name: spark-hb-nginx
        ports:
        - containerPort: 9999
          protocol: TCP
        readinessProbe:
          failureThreshold: 120
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          tcpSocket:
            port: 9999
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            ephemeral-storage: 500Mi
            memory: 128Mi
          requests:
            cpu: 100m
            ephemeral-storage: 500Mi
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/nginx
          name: spark-hb-nginx-configmap
        - mountPath: /etc/nginx/config/ssl
          name: internal-tls
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 2000
        runAsUser: 1000
      serviceAccount: {{ .Values.serviceAccount.wxdServiceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.wxdServiceAccount.name }}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: spark-hb-nginx-configmap
        name: spark-hb-nginx-configmap
      - name: internal-tls
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: cert.crt
          - key: tls.key
            path: cert.key
          secretName: internal-tls
