apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    function: spark-hb-ui
  name: spark-hb-ui
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "11"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      function: spark-hb-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        function: spark-hb-ui
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: PORT
          value: "8443"
        - name: LOG_LEVEL
          value: INFO
        - name: SSL_KEY
          value: /opt/app-root/src/internal-tls/tls.key
        - name: SSL_CERT
          value: /opt/app-root/src/internal-tls/tls.crt
        - name: NODE_EXTRA_CA_CERTS
          value: /opt/app-root/src/internal-tls/ca.crt
        image: {{ .Values.images.registry }}/{{ .Values.images.image.sparkUi }}{{ .Values.images.tag.sparkUi }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls
            - /opt/app-root/src/cpd-config/deployment.properties
          failureThreshold: 120
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        name: spark-hb-ui
        ports:
        - containerPort: 8443
          protocol: TCP
        readinessProbe:
          failureThreshold: 15
          httpGet:
            path: /analytics-engine/health/ping
            port: 8443
            scheme: HTTPS
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 30
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/app-root/src/cpd-config
          name: spark-hb-cp-deployment-properties
        - mountPath: /opt/app-root/src/internal-tls
          name: internal-tls
        - mountPath: /opt/app-root/src/cpd-confidential-config
          name: spark-hb-ui-cpd-confidential-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: {{ .Values.serviceAccount.wxdServiceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.wxdServiceAccount.name }}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: deployment-properties
            path: deployment.properties
          name: spark-hb-deployment-properties
        name: spark-hb-cp-deployment-properties
      - name: internal-tls
        secret:
          defaultMode: 420
          secretName: internal-tls
      - name: spark-hb-ui-cpd-confidential-config
        secret:
          defaultMode: 420
          secretName: spark-hb-confidential-properties
