apiVersion: v1
kind: Service
metadata:
  labels:
    app: lhams-api
  name: {{ .Values.service.consoleAms.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.service.consoleAms.port }}
    protocol: TCP
    targetPort: {{ .Values.service.consoleAms.port }}
  selector:
     app: lhams-api
  type: {{ .Values.service.consoleAms.type }}