apiVersion: v1
kind: Service
metadata:
  labels:
    app: lhconsole-nodeclient
  name: lhconsole-nodeclient-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: lhconsole-nodeclient
  type: ClusterIP