apiVersion: v1
kind: Service
metadata:
  labels:
    app: lhingestion-api
  name: lhingestion-api-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 7898
    protocol: TCP
    targetPort: 7898
  selector:
    app: lhingestion-api
  type: ClusterIP