apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: pg-postgres
  name: ibm-lh-postgres-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app.kubernetes.io/name: pg-postgres
  type: ClusterIP