apiVersion: v1
kind: Service
metadata:
  name: spark-hb-deployer-agent
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    function: spark-hb-deployer-agent
  type: ClusterIP