apiVersion: v1
kind: Service
metadata:
  labels:
    function: spark-hb-nginx
  name: spark-hb-nginx-external
  namespace: {{ .Release.Namespace }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: proxy
    nodePort: 30005
    port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    function: spark-hb-nginx
  type: NodePort