apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "ibm-lh-catalog-pvc"
  namespace:  {{ .Release.Namespace }}
  labels:
    function: "ibm-lh-catalog-pvc"
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.pvc.storageClassName }}