apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    function: spark-hb-control-plane-logs
  name: spark-hb-control-plane-logs
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.pvc.storageClassName }}