apiVersion: v1
data:
  users.htpasswd: {{ .Values.security.secrets.lhauthSecret.data | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.security.secrets.lhauthSecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque