apiVersion: v1
data:
  check-startup-probe.sh: |-
    #!/bin/bash

    exec_cmd()
    {
        CMD=$1
        message=$2
        response=$($CMD)
        response_code=${response: -3}
        if [[ "$response_code" == "200" ]]
        then
            echo "Ping successful on $message"
        else
            echo "Fail to ping on $message, response: $response_code"
            exit 1
        fi
    }

    ############# service provider #############
    exec_cmd "curl -s http://localhost:9080/v1/ping -w %{http_code} " "service provider"

    ############# Instance Manager service  #############
    exec_cmd "curl -s http://localhost:9080/instance_manager/v1/instance/ping -w %{http_code}" "Instance Manager service "

    ############# Access controller service  #############
    exec_cmd "curl -s http://localhost:9080/access/v1/apikey/ping -w %{http_code}" "Access controller service"

    ############# DataplaneManager service  #############
    exec_cmd "curl -s http://localhost:9080/dataplane_manager/v1/dataplane/ping -w %{http_code}" "DataplaneManager service"

    ############# job service  #############
    exec_cmd "curl -s http://localhost:9080/jobService/v1/ping -w %{http_code}" "job service"

    ############# kernel service  #############
    exec_cmd "curl -s http://localhost:9080/ae/ping -w %{http_code}" "kernel service"
kind: ConfigMap
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
  name: spark-hb-controlplane-probe
  namespace: {{ .Release.Namespace }}