apiVersion: v1
data:
  confidential.properties: {{ .Values.security.secrets.spark.confidentialProperties.data.confidentialProperties | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.security.secrets.spark.confidentialProperties.name }}
  namespace: {{ .Release.Namespace }}
type: {{ .Values.security.secrets.spark.confidentialProperties.type }}
