apiVersion: v1
data:
  token: {{ .Values.security.secrets.spark.zenServiceBrokerSecret.data.token | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.security.secrets.spark.zenServiceBrokerSecret.name }}
  namespace: {{ .Release.Namespace }}
type: {{ .Values.security.secrets.spark.zenServiceBrokerSecret.type }}