apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lhconsole-ui
  name: lhconsole-ui
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "8" 
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.deployment.replicas.consoleUI }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: lhconsole-ui
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable }}
    type: {{ .Values.deployment.strategy.type }}
  template:
    metadata:
      labels:
        app: lhconsole-ui
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: wxd-launch-cm
        image: {{ .Values.images.registry }}/{{ .Values.images.image.consoleUI }}:{{ .Values.images.tag.consoleUI }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        name: lh-container
        ports:
        - containerPort: 8443
          protocol: TCP
        resources: {{ .Values.deployment.resources.consoleUI | toYaml | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: {{ .Values.volumeMounts.internalTls }}
          name: internal-tls
        - mountPath: {{ .Values.volumeMounts.tls }}
          name: internal-tls-mount
        - mountPath: {{ .Values.volumeMounts.configSecret }}
          name: ibm-lh-config-secret-mount
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: {{ .Values.serviceAccount.wxdServiceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.wxdServiceAccount.name }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: internal-tls
        secret:
          defaultMode: 420
          secretName: {{ .Values.security.secrets.internalTls.name }}
      - name: internal-tls-mount
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: truststore.jks
                path: lh-ssl-ts.jks
              - key: keystore.jks
                path: lh-ssl-ks.jks
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
              - key: ca.crt
                path: ca.crt
              name: {{ .Values.security.secrets.internalTls.name }}
      - name: ibm-lh-tls-pem-mount
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: cabundle.crt
                path: tls-ca-bundle.pem
              name: {{ .Values.security.secrets.internalTls.name }}
      - name: ibm-lh-config-secret-mount
        secret:
          defaultMode: 420
          secretName: {{ .Values.security.secrets.configSecret.name }}

# Made with Bob
