apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lhconsole-api
  name: lhconsole-api
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "8"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: lhconsole-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lhconsole-api
    spec:
      containers:
      - env:
        - name: LH_CP4D_INTERNAL_NGINX_SVC
          value: https://{{ .Values.service.consoleUi.name }}:{{ .Values.service.consoleUi.port }}
        - name: LH_CP4D_SKIP_CA_FIELD
          value: InsecureSkipVerify
        envFrom:
        - configMapRef:
            name: wxd-launch-cm
        image: {{ .Values.images.registry }}/{{ .Values.images.image.lhconsoleApi }}:{{ .Values.images.tag.lhconsoleApi }}
        imagePullPolicy: IfNotPresent
        name: lh-container
        ports:
        - containerPort: 3333
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/infra/internal-tls
          name: internal-tls
        - mountPath: /mnt/infra/tls
          name: internal-tls-mount
        - mountPath: /mnt/infra/ibm-lh-secrets
          name: ibm-lh-config-secret-mount
        - mountPath: /lhconfig/milvus-privileges.json
          name: milvus-config
          subPath: milvus-privileges.json
        - mountPath: /mnt/infra/spark/service-id-credentials
          name: spark-hb-cp-wdp-secret
          subPath: wdp.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: {{ .Values.serviceAccount.wxdServiceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.wxdServiceAccount.name }}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: milvus-privileges-config
        name: milvus-config
      - name: internal-tls
        secret:
          defaultMode: 420
          secretName: internal-tls
      - name: spark-hb-cp-wdp-secret
        secret:
          defaultMode: 420
          items:
          - key: service-id-credentials
            path: wdp.properties
          secretName: wdp-service-id
      - name: internal-tls-mount
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: truststore.jks
                path: lh-ssl-ts.jks
              - key: keystore.jks
                path: lh-ssl-ks.jks
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
              - key: ca.crt
                path: ca.crt
              name: internal-tls
      - name: ibm-lh-tls-pem-mount
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: cabundle.crt
                path: tls-ca-bundle.pem
              name: internal-tls
      - name: ibm-lh-config-secret-mount
        secret:
          defaultMode: 420
          secretName: ibm-lh-config-secret
